#!/bin/sh

set -e

STOW_PACKAGES_PATH="$HOME"/dotfiles/packages

for i in "$@"; do
    case "$i" in
       -s|--skip-apps)
            skip_apps=1
            shift ;;
        *) ;;
    esac
done

log() {
    echo "[INFO] $1"
}

ensure_dir() {
    mkdir -p "$1"
}

###########################################################
# Install Homebrew
###########################################################
if [ ! -f /opt/homebrew/bin/brew ]; then
    log 'Setup Homebrew'
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if [ ! -d "$HOME"/dotfiles ]; then
    log 'Clone dotfiles'
    cd "$HOME"
    git clone https://github.com/a1yama/dotfiles.git
fi

if [ -z "$skip_apps" ]; then
    log 'Install Apps and CLIs'
    brew bundle --file "$HOME"/dotfiles/Brewfile
fi

###########################################################
# Stow link
###########################################################
log 'Link dotfiles'
ensure_dir ~/.config
ensure_dir ~/.config/nvim
ensure_dir ~/.config/lazygit
ensure_dir ~/.claude
ensure_dir ~/.codex

stow -vd "$STOW_PACKAGES_PATH" -t "$HOME" $(ls "$STOW_PACKAGES_PATH")

###########################################################
# Install yazi plugins
###########################################################
log 'Install yazi plugins'
if command -v ya >/dev/null 2>&1; then
    XDG_CONFIG_HOME="$HOME"/dotfiles/packages/yazi/.config \
    XDG_DATA_HOME="$HOME"/dotfiles/packages/yazi/.local/share \
    XDG_STATE_HOME="$HOME"/dotfiles/packages/yazi/.local/state \
    XDG_CACHE_HOME="$HOME"/dotfiles/packages/yazi/.cache \
    ya pkg install
else
    log 'yazi is not installed, skipping plugin installation'
fi

###########################################################
# Install tmux plugins (TPM)
###########################################################
log 'Install tmux plugins'
if [ ! -d "$HOME"/.tmux/plugins/tpm ]; then
    git clone https://github.com/tmux-plugins/tpm "$HOME"/.tmux/plugins/tpm
fi
"$HOME"/.tmux/plugins/tpm/bin/install_plugins

###########################################################
# create local config files
###########################################################
log 'Create local config files'
touch ~/.zsh/local.zsh
touch ~/.config/git/config.d/local.conf
