#!/bin/sh

set -e

STOW_PACKAGES_PATH="$HOME"/dotfiles/packages

log() {
    echo "[INFO] $1"
}

ensure_dir() {
    mkdir -p "$1"
}

###########################################################
# Install Homebrew
###########################################################
if [ ! -f /opt/homebrew/bin/brew ]; then
    log 'Setup Homebrew'
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if [ ! -d "$HOME"/dotfiles ]; then
    log 'Clone dotfiles'
    cd "$HOME"
    git clone https://github.com/a1yama/dotfiles.git
fi

if [ -z "$skip_apps" ]; then
    log 'Install Apps and CLIs'
    brew bundle --file "$HOME"/dotfiles/Brewfile
fi

###########################################################
# Stow link
###########################################################
log 'Link dotfiles'
ensure_dir ~/.config
ensure_dir ~/.config/nvim

stow -vd "$STOW_PACKAGES_PATH" -t "$HOME" $(ls "$STOW_PACKAGES_PATH")

###########################################################
# create zsh export files
###########################################################
log 'Create zsh local files'
touch ~/.zsh/local.zsh
