"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[character]
success_symbol = "[❯](bold #00ff00)"
error_symbol = "[✘](bold #ff4444)"

[directory]
truncation_length = 10
truncation_symbol = '…/'
style = "bold #00FFFF"
truncate_to_repo = false

[time]
disabled = false
format = "[$time]($style) "
style = "bold #ffff00"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'
modified = '[!\($count\)](green)'
untracked = '[?\($count\)](red)'
staged = '[++\($count\)](green)'
