format = """
$directory\
$git_branch\
$git_status\
$time"""

add_newline = false

[directory]
format = "[ $path ]($style)"
truncation_length = 10
truncate_to_repo = false
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[time]
disabled = false
time_format = "%R"
format = '[[  $time ](fg:#a0a9cb)]($style)'
